### ISSUE TITLE
How to run code

### ISSUE THREAD

**Issue by saeedizade** [varunranga/GrCluster#1]
Hi
Is there any guide about how to run code and reproduce the results?
I want to add WN18RR and run your code. However, I cannot even run the default code.

**Comment by varunranga** [comment]
Please take a look at "Supplementary Material.pdf" in the repository.

**Comment by saeedizade** [comment]
I ran " !python main.py" the output:

```
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    session = tensorflow.Session()
AttributeError: module 'tensorflow' has no attribute 'Session'

```

**Comment by varunranga** [comment]
Please look at the dependencies and their versions. The tensorflow version you need to be using is 1.12; but I suspect you are using tensorflow2+. You can get tensorflow1 through "import tensorflow.compat.v1 as tensorflow", or Install tensorflow==1.12

**Comment by saeedizade** [comment]
Does this model improve WN18RR?

**Comment by saeedizade** [comment]
Does this model improve WN18RR?
